# Plugin version 1.0.0

messages:
  invalidcommand: '§cThe command was entered incorrectly'
  wrongclanname: '§cWrong clan name'
  wrongplayername: '§cWrong player name'
  clannametaken: '§cThis clan name is already taken'
  youmemberclan: '§eYou are already a member of a clan'
  younotmemberclan: '§eYou are not a member of a clan'
  younotmemberthisclan: '§eYou are not a member of this clan'
  successcreateclan: '§aYou have successfully created a clan'
  notleader: '§eYou are not the leader of this clan'
  successdeleteclan: '§aClan successfully deleted'
  playermemberclan: '§eThis player is already in the clan'

roles:
  leader: 'Leader'
  elder: 'Elder'
  member: 'Member'
  noclan: 'null'