# Plugin version 1.0.0

messages:
  invalidcommand: '§cThe command was entered incorrectly'
  wrongclanname: '§cWrong clan name'
  wrongcolorname: '§cWrong color name'
  wrongplayername: '§cWrong player name'
  wrongrolename: '§cWrong role name'
  clannametaken: '§eThis clan name is already taken'
  youmemberclan: '§eYou are already a member of a clan'
  younotmemberclan: '§eYou are not a member of a clan'
  younotmemberthisclan: '§eYou are not a member of this clan'
  successcreateclan: '§bYou have successfully created the§r §e§l%clan%§r §bclan'
  notleader: '§eYou are not the leader of this clan'
  norightsinvite: '§eYou do not have enough rights to invite a player'
  norightssetrole: '§eYou do not have enough rights to change the player role'
  norightskick: '§eYou do not have enough rights to kick a player'
  alreadysentinvitation: '§eAt the moment, someone has already sent an invitation to this player'
  invitationsent: '§bThe invitation has been sent'
  successdeleteclan: '§bThe§r §e§l%clan%§r §bclan was successfully deleted§r'
  leaderdeleteclan: '§bThe leader of your clan has decided to delete the clan'
  playermemberclan: '§eThis player is already in the clan'
  playernotmemberclan: '§eThe player is not a member of a clan'
  invitation: '§bYou have received an invitation to the§r §e§l%clan%§r §bclan from the player§r §e§l%player%§r'
  clickinvite: 'Click to accept the invitation'
  accept: '§bAccept§r §e§l[✔]§r'
  younotinvited: '§eYou have no active invitations'
  sendinvitationyourself: '§eYou cannot send an invitation to yourself'
  successfullyjoinedclan: '§bYou have successfully joined the clan§r §e§l%clan%§r'
  playerjoined: '§bPlayer§r §e§l%player%§r §bjoined the clan'
  playernotyourclan: '§eThis player is not in your clan'
  roleishigher: '§eYou cannot kick a player because his role is higher or the same as yours'
  playerwaskicked: '§bPlayer§r §e§l%player%§r §bwas kicked out of the clan'
  kickyourself: '§eYou cannot kick yourself out'
  youwaskicked: '§bYou were kicked out of the§r §e§l%clan%§r §bclan'
  youleader: '§eYou cannot leave the clan because you are leader'
  playerleave: '§bPlayer§r §e§l%player%§r §bleft the clan'
  successfullyleft: '§bYou have successfully left the§r §e§l%clan%§r §bclan'
  notsetleader: '§eYou cannot set a player to be a leader'
  youbeenassigned: '§bYou have been assigned the role of§r §e§l%role%§r'
  successfullychangedrole: '§bYou have successfully changed the role of a player'

roles:
  leader: 'Leader'
  elder: 'Elder'
  member: 'Member'
  noclan: 'null'